### ISSUE TITLE
App keeps crashing on Homey V5

### ISSUE THREAD

**Issue by Allram** [jonkristian/no.jonkristian.octoprint#1]
Tried to install the app by CLI.
But i get the following crashlog, and the app is constantly crashing.

![Screenshot_20210211_091521_app homey](https://user-images.githubusercontent.com/5573149/107614191-1cb5fa80-6c4a-11eb-957c-db86cb842548.jpg)

**Comment by jonkristian** [comment]
Hello. I'm sorry that you are seeing this. Can you please try `npm install` before running this app, looks like a dependency is missing.

**Comment by Allram** [comment]
That fixed the problem, thanks!
