### ISSUE TITLE
Toolhead temp = bed temp ? Toolhead temp is not visible 

### ISSUE THREAD

**Issue by Allram** [jonkristian/no.jonkristian.octoprint#5]
Hello,

I have a Prusa Mini connected to Octoprint, and you can see here what the actual temp is:
![Temp](https://user-images.githubusercontent.com/5573149/107827361-eb8f1480-6d86-11eb-8d73-51d057696245.PNG)

In the app i get this:
![Screenshot_20210212_230359_app homey](https://user-images.githubusercontent.com/5573149/107827371-f053c880-6d86-11eb-9ecd-0d62863fe0eb.jpg)

So it seems like it uses the Bed temp for both BED and Tool temps.

**Comment by jonkristian** [comment]
Hi. Thanks for reporting. 
Could you please run this curl command, replace with your token and address then paste what comes back?

`curl -X 'GET' -H 'Content-Type: application/json' -H 'Authorization: Bearer REPLACE-WITH-YOUR-TOKEN' your-octoprint.address/api/printer`

**Comment by jonkristian** [comment]
Please use this to test: [Homey OctoPrint Test](https://homey.app/no-no/app/no.jonkristian.octoprint/Octoprint/test/)
I've found and fixed a bug in the code that made the nozzle temperature readings read from the bed.

**Comment by Allram** [comment]
Fixed with your latest test-version v1.0.6 :)
