### ISSUE TITLE
No snapshots are send

### ISSUE THREAD

**Issue by fvhuizen** [jonkristian/no.jonkristian.octoprint#6]
I love the app, now the printer is part of my home automation. But if i send a snapshot i just get the Homey logo shown. Is there something else which needs to be configured for that functionality. My webcam and snapshot settings in Octoprint works fine.

**Comment by jonkristian** [comment]
Thanks! :)

At the moment we pull the snapshot from the default octoprint url, it goes like this: `http://your-address/webcam/?action=snapshot`
Can you confirm if you get a snapshot from that address, or do you have some other address? 

The plan is to make this an option when setting up the device but we haven't gotten that far yet. Then potentially one could use whatever stream they'd like :)

**Comment by fvhuizen** [comment]
Hi Jon, i can get a stream when i send it by homey e.g. to a Google Hub. But the snapshots don't work, only if i test it on Octoprint it selves. Besides that i didn't get notipficated when a job is finished. So maybe there are some security issues.

**Comment by jonkristian** [comment]
Hmm. Do you use the default octoprint webcam address like i mentioned above? Also, if you go to that address in your browser do you get a static image output? And are there any isolation between octoprint and homey? And could you send a diagnostics report from app settings?

**Comment by jonkristian** [comment]
I've added an option to specify snapshot url in test now, so if you'd like to try it you can install from [here](https://homey.app/a/no.jonkristian.octoprint/test/).

**Comment by fvhuizen** [comment]
Hi Jon, this is my DR f1dc8e01-5932-45cd-a0b9-431edcc3c00c
I did update it with the link above, but where can i find the specific URL for snapshots

**Comment by jonkristian** [comment]
Unfortunately you'll have to remove and add the device again. I see nothing wrong in your report so that's good.

**Comment by fvhuizen** [comment]
Hi Jon, i tried to reïnstall the printer, but unfortunately i still got no snapshots while the snapshot tag is available. It just sends the Atom logo as snapshot :-( But probably it's not a issue from the app. I only can get a snapshot from Octoprint by pushing the test button. If i try to di it manually wit the IP adres from Octoprint i get errors, So i don't know what i need to change for that.

**Comment by jonkristian** [comment]
Thanks for your information and testing. We're working on homey sdk 3 now and with more improvements. We will focus on snapshots and we've also confirmed that something is not right there. Are you on v5? There will be some new code here on github for testing if you'd like to try it I will let you know when. If you're not on v5 just yet we are considering putting out a patch for sdk 2 that works.

**Comment by fvhuizen** [comment]
Hi Jon, i'm since December on V5, so yes i like to test that part. Besides that i managed to get Snapshots from Octoprint manually on a browser Windows by triggering https://192.168.2.86/webcam/?action=snapshot and it comes back with a decent snapshot. When putting the URL in Homey it still sends the logo :-) And i didn't print that. Looking forward for a link for testing purposes

**Comment by jonkristian** [comment]
I've been looking into flows. The `printFinished` with snapshot and duration is triggered programmatically when a print is finished. Did you test this while printing or did you only try to trigger with test?

**Comment by fvhuizen** [comment]
I tested on print jobs which are finished, so real finishing. Besides that i can't get the app working anymore. I added the printer like you suggested and now i don't see realtime information from the printer. So everything is stated with just a score.

**Comment by jonkristian** [comment]
Hi. Sorry you're experiencing difficulties. I've created a new branch called [develop](https://github.com/jonkristian/no.jonkristian.octoprint/tree/develop) which now has the most recent code for sdk 3. If you could try that, re-add your device and see? I would be grateful. The snapshot url should then be located under advanced settings on the device if you need to change it.

I've made the snapshot token global, so it should now be possible to request a snapshot whenever. Also, adding the device should be easier and give some feedback if it fails to ping.

**Comment by fvhuizen** [comment]
Sorry to say but installing isn't working. I got the next error
MacBook-Pro:octo Frans$ homey app install
-bash: homey: command not found

**Comment by jonkristian** [comment]
A little more involvement required to install like this unfortunately. If you want to try you could follow this video tutorial https://www.youtube.com/watch?v=lRZLvhF2sfk

... but if not I understand. I am waiting for another tester before putting it out on homey test, but I can let you know once it's out there.

**Comment by fvhuizen** [comment]
I did install SW many times in the past with CLI. But in this case i will leave it until it becomes more stable. Thank you anyway

**Comment by jonkristian** [comment]
I'll let you know as soon as it hits test.

**Comment by fvhuizen** [comment]
Hi Jon, i have just one request. I managed to install the first version you pointed me too. But what is bothering me that if the printer is printing and i want to go to the printer in the Homey app, it's annoying when you touch the printer button and want to go to the overview you easily turn you printer off. Can the on/off button be moved or set else way?
Still looking forward to the improved version for V5 where snapshot can be send.
Best regards.

**Comment by jonkristian** [comment]
Hello. Are you on the latest develop branch now? If so, I would love to get feedback if everything is alright. Are you getting snapshot now? 

Regarding the power onoff button I agree, it's not a good UX decision or at least there should be a way to confirm if one unintentionally touches.  I did actually implement a feature here that if it's printing you can't turn it off by accident, is this not working?

I will have to take a second look at this and see what solution I can come up with.

**Comment by fvhuizen** [comment]
Hi Jon, I've installed V.0.6 but it's not stable so far. I'm glad you agree on the on/off location. Yesterday i broke up unintentionally a print and couldn't get it started again. So i will wait for a more stable version to work with. And about snapshots, that part isn't working here. And triggering a snapshot manually works when i use this is a browser on the same network https://192.168.2.86/webcam/?action=snapshot.

**Comment by jonkristian** [comment]
Wow, sorry :/. That's not good and it shouldn't happen. I wonder how, are you sure it got turned off from the card in homey while printing? Because i specifically set it to not turn off while printing. But it could happen if the polling interval is set too high and the state hasn't been updated yet.

```
    this.registerCapabilityListener('onoff', async (value) => {
      if ( false == value ) {
        // Don't set off while printing.
        if ( 'Printing' !== this.printer.state.cur ) {
          this.octoprint.postData('/api/connection', {command:'disconnect'});
        }
      } else {
        this.octoprint.postData('/api/connection', {command:'connect'});
      }
    });
```

By the way if you could test this again it would mean a lot, and you can do so without breaking anything. There's a virtual printer in OctoPrint under settings you can enable which would give you the ability to emulate a printer :) Just activate and disconnect real printer and re-connect to the new one called VIRTUAL.

**Comment by fvhuizen** [comment]
For now i will leave it as it is, today i don't get connected like it seems. There is no real info at the app side. So i'm sorry but i will get back if there is an app that is more stable and functional. But i love the idea that we can get info in homey about status and snapshots.

**Comment by jonkristian** [comment]
I understand. Some news, I've been looking at onoff and found out it's being triggered still, even though I don't call the actual printer disconnect, it will trigger flows e.g. if you have the printer on an outlet. This is taken care of in develop branch now and will be fixed with 1.0.7.

**Comment by jonkristian** [comment]
Should be fixed in 1.0.7, now available in [test](https://homey.app/a/no.jonkristian.octoprint/test/).

**Comment by fvhuizen** [comment]
Sorry to tell you, but the next thing is happening. To be sure everything works i removed the printer and added it again. I deleted the old API key and generated a new one and saved it. After adding the printer and setting the credentials i got the next error; flow token_already_exists

**Comment by jonkristian** [comment]
I've seen this too, I'm not sure what happened and I couldn't reproduce it after it happened, but if you restart the app it should work.

**Comment by jonkristian** [comment]
Should be fixed now, in 1.0.8 which I just published to test.

PS: If you experience any new issues, please feel free to create new ones, so we can keep things tidy.

**Comment by fvhuizen** [comment]
Okay great, fyi the app version 1.0.7 works great after rebooting the app, even the snapshots are send now.
Great job Jon, thx

**Comment by jonkristian** [comment]
Thanks. Remember when you go up to 1.0.8 you have to re-check your flows.
