### ISSUE TITLE
Getting flow_token_already_exists in 1.0.8

### ISSUE THREAD

**Issue by nerdtechse** [jonkristian/no.jonkristian.octoprint#8]
Tried 1.0.8 version on my homey but got a red mark on the device and when i click on it i get "flow_token_already_exists"

**Comment by jonkristian** [comment]
Did you have previous ver. installed before? Did this happen on a newly added device? To be sure, remove and re-add the device and restart the app. Let me know if the problem still occurs.

**Comment by nerdtechse** [comment]
So true tried a earlier version.. And deleted the device before. But i didnt restart the app.. Now after restart it works! :) 

Thanks for fast answer and a great app!
