### ISSUE TITLE
flow_token_already_exists in 1.0.8 for second printer

### ISSUE THREAD

**Issue by rickyhoots** [jonkristian/no.jonkristian.octoprint#9]
Saw the former issues so deleted all devices, reinstalled the app and re-added the printers.

First one goes ok, second adds ok as well but after returning it has the red mark with the error flowtoken_already_exists error.

Did a diagnostic report: cc4e64b4-bf87-4900-a22a-3d08d41a84eb

**Comment by jonkristian** [comment]
Hm, that's strange. Nothing out of the ordinary in your report except for that error, which is a remote error and kinda hard to debug. What happens if you just do a reboot, do they work then? I have yet to test on multiple octoprint servers but will find the time to do that asap.

**Comment by jonkristian** [comment]
@rickyhoots I've confirmed a bug with multiple printers. I've pushed the fix to [test](https://homey.app/a/no.jonkristian.octoprint/test/) now, would you mind trying that one? I've also added in-app camera.

**Comment by rickyhoots** [comment]
After a ptp on the homey and power cycles/reboots on the octopi’s it started working this morning but will test the test version as-well. Is there a need to delete and redo the flows or is a simple update to the test version enough?

**Comment by jonkristian** [comment]
A simple update is enough for devices, no need to re-add, however the snapshot is now part of the device as an image, so if you use snapshot in your flows you might want to check that bit.

**Comment by jonkristian** [comment]
I'm closing this for now, feel free to open again if the problem re-occurs.
